-------------------------------------------
--Unit (Qursan)
-------------------------------------------
INSERT INTO Units
		(Type,				Description,				Civilopedia,							Strategy,							Help,							Combat,	Cost,	Moves,	BaseSightRange,	Class,	CombatClass,	Domain,		DefaultUnitAI,		MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	PrereqTech,	ObsoleteTech,	HurryCostModifier,	AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	UnitArtInfo,				ShowInPedia,	MoveRate,	UnitFlagIconOffset,	PortraitIndex,	IconAtlas,						UnitFlagAtlas)
SELECT	'UNIT_JWW_QURSAN',	'TXT_KEY_UNIT_JWW_QURSAN',	'TXT_KEY_CIV5_UNIT_JWW_QURSAN_TEXT',	'TXT_KEY_UNIT_JWW_QURSAN_STRATEGY',	'TXT_KEY_UNIT_HELP_JWW_QURSAN',	Combat,	Cost,	Moves,	BaseSightRange,	Class,	CombatClass,	Domain,		DefaultUnitAI,		MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	PrereqTech,	ObsoleteTech,	HurryCostModifier,	AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	'ART_DEF_UNIT_JWW_QURSAN',	ShowInPedia,	MoveRate,	0,					2,				'JWW_TETOUAN_COLOR_ATLAS',	'JWW_TETOUAN_UNIT_ALPHA_ATLAS'
FROM Units WHERE Type = 'UNIT_PRIVATEER';

INSERT INTO UnitGameplay2DScripts
		(UnitType,					SelectionSound,		FirstSelectionSound)
SELECT	'UNIT_JWW_QURSAN',	SelectionSound,		FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_PRIVATEER';

INSERT INTO Unit_AITypes
		(UnitType,					UnitAIType)
SELECT	'UNIT_JWW_QURSAN',	UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_PRIVATEER';

INSERT INTO Unit_Flavors
		(UnitType,					FlavorType,			Flavor)
SELECT	'UNIT_JWW_QURSAN',	FlavorType,			Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_PRIVATEER';

INSERT INTO Unit_ClassUpgrades
		(UnitType,					UnitClassType)
SELECT	'UNIT_JWW_QURSAN',	UnitClassType
FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_PRIVATEER';

INSERT INTO Unit_FreePromotions
		(UnitType,			PromotionType)
SELECT	'UNIT_JWW_QURSAN',	PromotionType
FROM Unit_FreePromotions WHERE UnitType = 'UNIT_PRIVATEER';

INSERT INTO UnitPromotions
		(Type,											Description,										Help,													Sound,				CannotBeChosen,	NearbyEnemyCombatMod,	NearbyEnemyCombatRange,	PortraitIndex,	IconAtlas,			PediaType,			PediaEntry)
VALUES	('PROMOTION_JWW_TETOUAN_QURSAN_WEAKEN',			'TXT_KEY_PROMOTION_JWW_TETOUAN_QURSAN_WEAKEN',		'TXT_KEY_PROMOTION_JWW_TETOUAN_QURSAN_WEAKEN_HELP',		'AS2D_IF_LEVELUP',	1,				-20,					1,						59,				'ABILITY_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_QURSAN_WEAKEN');
-------------------------------------------
--Building (Mazmorra)
-------------------------------------------
INSERT INTO Buildings
		(Type,						Description,						Civilopedia,								Strategy,									Help,									MutuallyExclusiveGroup,	NeverCapture,	NukeImmune,	Cost,	HurryCostModifier,	MinAreaSize,	BuildingClass,	ArtDefineTag,	PrereqTech,	PortraitIndex,	WonderSplashAnchor,	IconAtlas)
SELECT	'BUILDING_JWW_MAZMORRA',	'TXT_KEY_BUILDING_JWW_MAZMORRA',	'TXT_KEY_CIV5_BUILDINGS_JWW_MAZMORRA_TEXT',	'TXT_KEY_BUILDING_JWW_MAZMORRA_STRATEGY',	'TXT_KEY_BUILDING_JWW_MAZMORRA_HELP',	MutuallyExclusiveGroup,	1,				NukeImmune,	Cost,	HurryCostModifier,	MinAreaSize,	BuildingClass,	ArtDefineTag,	PrereqTech,	4,				WonderSplashAnchor,	'JWW_TETOUAN_COLOR_ATLAS'
FROM Buildings WHERE Type = 'BUILDING_MINT';

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,				ResourceType,	YieldType,	Yield)
SELECT	'BUILDING_JWW_MAZMORRA',	ResourceType,	YieldType,	Yield
FROM Building_ResourceYieldChanges WHERE BuildingType = 'BUILDING_MINT';

INSERT INTO	Building_Flavors
		(BuildingType,				FlavorType,	Flavor)
SELECT	'BUILDING_JWW_MAZMORRA',	FlavorType,	Flavor
FROM Building_Flavors WHERE BuildingType = 'BUILDING_MINT';

INSERT INTO Building_DomainProductionModifiers
		(BuildingType,				DomainType,		Modifier)
VALUES	('BUILDING_JWW_MAZMORRA',	'DOMAIN_SEA',	15);
-------------------------------------------
--Leader (Sayyida al-Hurra)
-------------------------------------------
INSERT INTO Leaders
		(Type,							Description,							Civilopedia,									CivilopediaTag,										ArtDefineTag,				VictoryCompetitiveness,	WonderCompetitiveness,	MinorCivCompetitiveness,	Boldness,	DiploBalance,	WarmongerHate,	WorkAgainstWillingness,	WorkWithWillingness,	DenounceWillingness,	DoFWillingness,	Loyalty,	Neediness,	Forgiveness,	Chattiness,	Meanness,	PortraitIndex,	IconAtlas)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',	'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA',	'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_PEDIA',	'TXT_KEY_CIVILOPEDIA_LEADERS_JWW_SAYYIDA_AL_HURRA',	'SayyidaAlHurraScene.xml',	7,						5,						4,							8,			5,				1,				9,						3,						9,						3,				6,			2,			1,				1,			7,			0,				'JWW_TETOUAN_COLOR_ATLAS');

INSERT INTO Leader_MajorCivApproachBiases
		(LeaderType,				MajorCivApproachType,			Bias)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_WAR',		7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_HOSTILE',	7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_DECEPTIVE',	8),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_GUARDED',	4),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_AFRAID',	1),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_FRIENDLY',	1),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MAJOR_CIV_APPROACH_NEUTRAL',	1);

INSERT INTO Leader_MinorCivApproachBiases
		(LeaderType,				MinorCivApproachType,				Bias)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',	'MINOR_CIV_APPROACH_IGNORE',		3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MINOR_CIV_APPROACH_FRIENDLY',		3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MINOR_CIV_APPROACH_PROTECTIVE',	3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MINOR_CIV_APPROACH_CONQUEST',		5),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'MINOR_CIV_APPROACH_BULLY',			7);

INSERT INTO	Leader_Flavors
		(LeaderType,				FlavorType,							Flavor)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_OFFENSE',					9),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_DEFENSE',					2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_CITY_DEFENSE',				6),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_MILITARY_TRAINING',			9),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_RECON',						3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_RANGED',					3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_MOBILE',					2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_NAVAL',						10),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_NAVAL_RECON',				10),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_NAVAL_GROWTH',				10),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_NAVAL_TILE_IMPROVEMENT',	6),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_AIR',						3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_EXPANSION',					5),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_GROWTH',					7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_TILE_IMPROVEMENT',			4),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_INFRASTRUCTURE',			7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_PRODUCTION',				9),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_GOLD',						7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_SCIENCE',					3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_CULTURE',					5),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_HAPPINESS',					5),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_GREAT_PEOPLE',				4),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_WONDER',					2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_RELIGION',					7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_DIPLOMACY',					4),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_SPACESHIP',					3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_WATER_CONNECTION',			7),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_NUKE',						5),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_USE_NUKE',					8),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_ESPIONAGE',					3),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_ANTIAIR',					2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_AIR_CARRIER',				6),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_ARCHAEOLOGY',				4),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_I_LAND_TRADE_ROUTE',		2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_I_SEA_TRADE_ROUTE',			6),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_I_TRADE_ORIGIN',			9),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_I_TRADE_DESTINATION',		2),
		('LEADER_JWW_SAYYIDA_AL_HURRA',	'FLAVOR_AIRLIFT',					3);

INSERT INTO Leader_Traits
		(LeaderType,					TraitType)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',	'TRAIT_JWW_PIRATE_QUEEN_OF_THE_WESTERN_SEAS');
-------------------------------------------
--Trait (Pirate Queen of the Western Seas)
-------------------------------------------
INSERT INTO Traits
		(Type,											Description,											ShortDescription)
VALUES	('TRAIT_JWW_PIRATE_QUEEN_OF_THE_WESTERN_SEAS',	'TXT_KEY_TRAIT_JWW_PIRATE_QUEEN_OF_THE_WESTERN_SEAS',	'TXT_KEY_TRAIT_JWW_PIRATE_QUEEN_OF_THE_WESTERN_SEAS_SHORT');

INSERT INTO UnitPromotions
		(Type,											Description,									Help,													Sound,				CannotBeChosen,	PortraitIndex,	IconAtlas,						PediaType,			PediaEntry)
VALUES	('PROMOTION_JWW_TETOUAN_CAPTIVES_0',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_0',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_0_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_0'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_1',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_1',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_1_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_1'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_2',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_2',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_2_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_2'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_3',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_3',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_3_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_3'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_4',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_4',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_4_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_4'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_5',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_5',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_5_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_5'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_6',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_6',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_6_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_6'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_7',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_7',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_7_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_7'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_8',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_8',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_8_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_8'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_9',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_9',		'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_9_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_9'),
		('PROMOTION_JWW_TETOUAN_CAPTIVES_10',			'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_10',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_10_HELP',		'AS2D_IF_LEVELUP',	1,				0,				'JWW_TETOUAN_PROMOTION_ATLAS',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_JWW_TETOUAN_CAPTIVES_10');

-------------------------------------------
--Diplomacy Responses
-------------------------------------------
INSERT INTO Diplomacy_Responses
		(LeaderType,						ResponseType,									 Response,																		Bias)
VALUES	('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_ATTACKED_HOSTILE',                     'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_ATTACKED_GENERIC%',						500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_DEFEATED',                             'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_DEFEATED%',								500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_DOW_GENERIC',                          'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_DOW_GENERIC%',							500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_EXPANSION_SERIOUS_WARNING',            'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_EXPANSION_SERIOUS_WARNING%',				500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_FIRST_GREETING',                       'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_FIRSTGREETING%',							500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_GREETING_AT_WAR_HOSTILE',				 'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_GREETING_AT_WAR_HOSTILE%',				500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_GREETING_POLITE_HELLO',                'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_GREETING_POLITE_HELLO%',					500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_GREETING_NEUTRAL_HELLO',               'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_GREETING_NEUTRAL_HELLO%',					500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_GREETING_HOSTILE_HELLO',               'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_GREETING_HOSTILE_HELLO%',					500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',  'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',	500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_INFLUENTIAL_ON_AI',                    'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_INFLUENTIAL_ON_AI%',						500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_INFLUENTIAL_ON_HUMAN',                 'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_INFLUENTIAL_ON_HUMAN%',					500),	
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_LETS_HEAR_IT',                         'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_LETS_HEAR_IT%',							500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_LUXURY_TRADE',                         'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_LUXURY_TRADE%',							500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_NO_PEACE',                             'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_NO_PEACE%',								500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_OPEN_BORDERS_EXCHANGE',                'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_OPEN_BORDERS_EXCHANGE%',					500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS',         'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_LOSEWAR%',								500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_REPEAT_NO',                            'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_REPEAT_NO%',								500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_RESPONSE_REQUEST',                     'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_RESPONSE_REQUEST%',						500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_RESPONSE_TO_BEING_DENOUNCED',		     'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_RESPONSE_TO_BEING_DENOUNCED%',			500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_TOO_SOON_NO_PEACE',                    'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_TOO_SOON_NO_PEACE_1%',					500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_WINNER_PEACE_OFFER',                   'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_WINWAR%',									500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_WORK_AGAINST_SOMEONE',                 'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_DENOUNCE%',								500),
		('LEADER_JWW_SAYYIDA_AL_HURRA',     'RESPONSE_WORK_WITH_US',                         'TXT_KEY_LEADER_JWW_SAYYIDA_AL_HURRA_DEC_FRIENDSHIP%',							500);
-------------------------------------------
--Civilization (Tétouan)
-------------------------------------------
INSERT INTO Civilizations
		(Type,							Description,					CivilopediaTag,					Playable,	AIPlayable,		ShortDescription,							Adjective,								DefaultPlayerColor,				ArtDefineTag,					ArtStyleType,				ArtStyleSuffix,		ArtStylePrefix,		PortraitIndex,			IconAtlas,					AlphaIconAtlas,				MapImage,					DawnOfManQuote,							DawnOfManImage)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CIV_JWW_TETOUAN_DESC',	'TXT_KEY_CIV5_JWW_TETOUAN',		1,			1,				'TXT_KEY_CIV_JWW_TETOUAN_SHORT_DESC',		'TXT_KEY_CIV_JWW_TETOUAN_ADJECTIVE',	'PLAYERCOLOR_JWW_TETOUAN',		'ART_DEF_CIVILIZATION_MOROCCO',	'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN',			1,						'JWW_TETOUAN_COLOR_ATLAS',	'JWW_TETOUAN_ALPHA_ATLAS',	'SayyidaAlHurraMap.dds',	'TXT_KEY_CIV5_DAWN_JWW_TETOUAN_TEXT',	'SayyidaAlHurraDOM.dds');

INSERT INTO Civilization_Leaders
		(CivilizationType,				LeaderheadType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'LEADER_JWW_SAYYIDA_AL_HURRA');

INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType,				BuildingClassType,				BuildingType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'BUILDINGCLASS_MINT',			'BUILDING_JWW_MAZMORRA');

INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType,				UnitClassType,			UnitType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'UNITCLASS_PRIVATEER',	'UNIT_JWW_QURSAN');

INSERT INTO Civilization_FreeBuildingClasses
		(CivilizationType,				BuildingClassType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs
		(CivilizationType,				TechType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'TECH_AGRICULTURE');

INSERT INTO Civilization_FreeUnits
		(CivilizationType,				UnitClassType,			UnitAIType,			Count)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'UNITCLASS_SETTLER',	'UNITAI_SETTLE',	1);

INSERT INTO Civilization_Start_Along_Ocean
		(CivilizationType,				StartAlongOcean)
VALUES	('CIVILIZATION_JWW_TETOUAN',	1);

INSERT INTO Civilization_Religions
		(CivilizationType,				ReligionType)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'RELIGION_ISLAM');

INSERT INTO	Civilization_CityNames
		(CivilizationType,				CityName)
VALUES	('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_0'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_1'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_2'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_3'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_4'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_5'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_6'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_7'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_8'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_9'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_10'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_11'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_12'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_13'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_14'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_15'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_16'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_17'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_18'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_19'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_20'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_21'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_22'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_23'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_24'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_25'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_26'),
		('CIVILIZATION_JWW_TETOUAN',	'TXT_KEY_CITY_NAME_JWW_TETOUAN_27');
		
INSERT INTO Civilization_SpyNames
		(CivilizationType,					SpyName)
VALUES	('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_0'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_1'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_2'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_3'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_4'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_5'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_6'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_7'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_8'),
		('CIVILIZATION_JWW_TETOUAN',		'TXT_KEY_SPY_NAME_JWW_TETOUAN_9');
--============================================	
--============================================
