-------------------------------------------
--Building (Igreja Costeira)
-------------------------------------------
INSERT INTO Buildings
		(Type,								Description,								Civilopedia,											Strategy,											Help,											GoldMaintenance,	MutuallyExclusiveGroup,	NeverCapture,	Cost,	HurryCostModifier,	MinAreaSize,	Espionage,	EspionageModifier,	BuildingClass,				ArtDefineTag,	PrereqTech,			PortraitIndex,	WonderSplashAnchor,	IconAtlas)
VALUES	('BUILDING_JWW_IGREJA_TIMORENSE',	'TXT_KEY_BUILDING_JWW_IGREJA_TIMORENSE',	'TXT_KEY_CIV5_BUILDINGS_JWW_IGREJA_TIMORENSE_TEXT',		'TXT_KEY_BUILDING_JWW_IGREJA_TIMORENSE_STRATEGY',	'TXT_KEY_BUILDING_JWW_IGREJA_TIMORENSE_HELP',	1,					-1,						1,				160,	25,					-1,				1,			-25,				'BUILDINGCLASS_CONSTABLE',	'COLESSEUM',	'TECH_BANKING',		4,				'R,T',				'JWW_TIMORLESTE_COLOR_ATLAS');

INSERT INTO	Building_Flavors
		(BuildingType,						FlavorType,			Flavor)
VALUES	('BUILDING_JWW_IGREJA_TIMORENSE',	'FLAVOR_ESPIONAGE',	25);

INSERT INTO BuildingClasses
		(Type, 									DefaultBuilding, 					Description)
VALUES	('BUILDINGCLASS_JWW_TL_UB_DUMMY', 		'BUILDING_JWW_TL_UB_DUMMY', 		'TXT_KEY_BUILDING_JWW_TL_UB_DUMMY');

INSERT INTO Buildings      
        (TYPE,                              BuildingClass,                          Cost,  FaithCost, GreatWorkCount,   NeverCapture,  Description)
VALUES  ('BUILDING_JWW_TL_UB_DUMMY',		'BUILDINGCLASS_JWW_TL_UB_DUMMY',        -1,    -1,        -1,               1,             'TXT_KEY_BUILDING_JWW_TL_UB_DUMMY');

INSERT INTO Building_UnitCombatFreeExperiences  
        (BuildingType,                    UnitCombatType,							Experience)
VALUES  ('BUILDING_JWW_TL_UB_DUMMY',	 'UNITCOMBAT_MELEE',                         15),
        ('BUILDING_JWW_TL_UB_DUMMY',	 'UNITCOMBAT_RECON',                         15),
        ('BUILDING_JWW_TL_UB_DUMMY',	 'UNITCOMBAT_ARCHER',                        15),
        ('BUILDING_JWW_TL_UB_DUMMY',	 'UNITCOMBAT_MOUNTED',                       15),
        ('BUILDING_JWW_TL_UB_DUMMY',	 'UNITCOMBAT_SIEGE',                         15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_GUN',							 15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_ARMOR',                         15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_HELICOPTER',                    15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_NAVALRANGED',                   15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_FIGHTER',                       15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_BOMBER',                        15),
        ('BUILDING_JWW_TL_UB_DUMMY',     'UNITCOMBAT_NAVALMELEE',                    15);

-------------------------------------------
--Unit (FALINTIL)
-------------------------------------------

INSERT INTO Units
		(Type,							Description,							Civilopedia,								Strategy,										Help,										Combat,	Cost,	FaithCost,	RequiresFaithPurchaseEnabled,	Moves,	BaseSightRange,	Class,					CombatClass,		Domain,			DefaultUnitAI,		MilitarySupport,	MilitaryProduction,	Pillage,	IgnoreBuildingDefense,	PrereqTech,			AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	UnitArtInfo,							ShowInPedia,	MoveRate,	UnitFlagIconOffset,	PortraitIndex,	IconAtlas,					UnitFlagAtlas)
VALUES	('UNIT_JWW_FORCAS_DA_FALINTIL',	'TXT_KEY_UNIT_JWW_FORCAS_DA_FALINTIL',	'TXT_KEY_CIV5_JWW_FORCAS_DA_FALINTIL_TEXT',	'TXT_KEY_UNIT_JWW_FORCAS_DA_FALINTIL_STRATEGY',	'TXT_KEY_UNIT_HELP_JWW_FORCAS_DA_FALINTIL',	65,		400,	800,		1,								2,		2,				'UNITCLASS_MARINE',		'UNITCOMBAT_GUN',	'DOMAIN_LAND',	'UNITAI_DEFENSE',	1,					1,					1,			1,						'TECH_PENICILIN',	40,					-1,				-1,					100,			3,				3,				'ART_DEF_UNIT_MARINE',	1,				'BIPED',	0,					2,				'JWW_TIMORLESTE_COLOR_ATLAS',	'JWW_TIMORLESTE_UNIT_ALPHA_ATLAS');

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
VALUES	('UNIT_JWW_FORCAS_DA_FALINTIL',	'UNITAI_ATTACK'),
		('UNIT_JWW_FORCAS_DA_FALINTIL',	'UNITAI_DEFENSE'),
		('UNIT_JWW_FORCAS_DA_FALINTIL',	'UNITAI_EXPLORE');

INSERT INTO Unit_FreePromotions
		(UnitType,						PromotionType)
VALUES	('UNIT_JWW_FORCAS_DA_FALINTIL',	'PROMOTION_AMPHIBIOUS'),
		('UNIT_JWW_FORCAS_DA_FALINTIL',	'PROMOTION_EMBARKED_SIGHT'),
		('UNIT_JWW_FORCAS_DA_FALINTIL',	'PROMOTION_DEFENSIVE_EMBARKATION');

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType,				Flavor)
VALUES	('UNIT_JWW_FORCAS_DA_FALINTIL',	'FLAVOR_OFFENSE',		20),
		('UNIT_JWW_FORCAS_DA_FALINTIL',	'FLAVOR_DEFENSE',		15);

INSERT INTO UnitGameplay2DScripts
		(UnitType,						SelectionSound,			FirstSelectionSound)
VALUES	('UNIT_JWW_FORCAS_DA_FALINTIL',	'AS2D_SELECT_INFANTRY',	'AS2D_BIRTH_INFANTRY');

INSERT INTO BuildingClasses
		(Type, 									DefaultBuilding, 					Description)
VALUES	('BUILDINGCLASS_JWW_TL_UU_TURN_DUMMY', 	'BUILDING_JWW_TL_UB_DUMMY', 		'TXT_KEY_BUILDING_JWW_TL_UU_TURN_DUMMY'),
		('BUILDINGCLASS_JWW_TL_UU_SAD_DUMMY', 	'BUILDING_JWW_TL_UU_SAD_DUMMY', 	'TXT_KEY_BUILDING_JWW_TL_UU_SAD_DUMMY');

INSERT INTO Buildings      
        (TYPE,                              BuildingClass,                          Cost,  FaithCost, GreatWorkCount,   NeverCapture,  Description)
VALUES  ('BUILDING_JWW_TL_UU_TURN_DUMMY',	'BUILDINGCLASS_JWW_TL_UU_TURN_DUMMY',   -1,    -1,        -1,               1,             'TXT_KEY_BUILDING_JWW_TL_UU_TURN_DUMMY');

INSERT INTO Buildings      
        (TYPE,                              BuildingClass,                          Cost,  FaithCost, GreatWorkCount,   NeverCapture,  UnhappinessModifier,	Description)
VALUES  ('BUILDING_JWW_TL_UU_SAD_DUMMY',	'BUILDINGCLASS_JWW_TL_UU_SAD_DUMMY',    -1,    -1,        -1,               1,             2,					'TXT_KEY_BUILDING_JWW_TL_UU_SAD_DUMMY');

INSERT INTO UnitPromotions
		(Type,						Description,					Help,								Sound,				CannotBeChosen,	DefenseMod,	PortraitIndex,	IconAtlas,			PediaType,		PediaEntry)
VALUES	('PROMOTION_JWW_TL_UU',		'TXT_KEY_PROMOTION_JWW_TL_UU',	'TXT_KEY_PROMOTION_JWW_TL_UU_HELP',	'AS2D_IF_LEVELUP',	1,				50,			59,				'ABILITY_ATLAS',	'PEDIA_SHARED',	'TXT_KEY_PROMOTION_JWW_TL_UU');

-------------------------------------------
--Leader (Xanana Gusmão)
-------------------------------------------

INSERT INTO Leaders
		(Type,							Description,						Civilopedia,								CivilopediaTag,										ArtDefineTag,			VictoryCompetitiveness,	WonderCompetitiveness,	MinorCivCompetitiveness,	Boldness,	DiploBalance,	WarmongerHate,	WorkAgainstWillingness,	WorkWithWillingness,	DenounceWillingness,	DoFWillingness,	Loyalty,	Neediness,	Forgiveness,	Chattiness,	Meanness,	PortraitIndex,	IconAtlas)
VALUES	('LEADER_JWW_XANANA_GUSMAO',	'TXT_KEY_LEADER_JWW_XANANA_GUSMAO',	'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_PEDIA',	'TXT_KEY_CIVILOPEDIA_LEADERS_JWW_XANANA_GUSMAO',	'GusmaoScene.xml',		5,						4,						6,							7,			8,				9,				3,						7,						8,						9,				5,			9,			2,				4,			1,			0,				'JWW_TIMORLESTE_COLOR_ATLAS');

INSERT INTO Leader_MajorCivApproachBiases
		(LeaderType,					MajorCivApproachType,			Bias)
VALUES	('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_WAR',		4),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_HOSTILE',	2),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_DECEPTIVE',	4),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_GUARDED',	9),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_AFRAID',	7),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_FRIENDLY',	10),
		('LEADER_JWW_XANANA_GUSMAO',	'MAJOR_CIV_APPROACH_NEUTRAL',	4);

INSERT INTO Leader_MinorCivApproachBiases
		(LeaderType,					MinorCivApproachType,				Bias)
VALUES	('LEADER_JWW_XANANA_GUSMAO',	'MINOR_CIV_APPROACH_IGNORE',		1),
		('LEADER_JWW_XANANA_GUSMAO',	'MINOR_CIV_APPROACH_FRIENDLY',		9),
		('LEADER_JWW_XANANA_GUSMAO',	'MINOR_CIV_APPROACH_PROTECTIVE',	6),
		('LEADER_JWW_XANANA_GUSMAO',	'MINOR_CIV_APPROACH_CONQUEST',		3),
		('LEADER_JWW_XANANA_GUSMAO',	'MINOR_CIV_APPROACH_BULLY',			2);

INSERT INTO	Leader_Flavors
		(LeaderType,					FlavorType,							Flavor)
VALUES	('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_OFFENSE',					3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_DEFENSE',					9),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_CITY_DEFENSE',				8),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_MILITARY_TRAINING',			6),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_RECON',						4),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_RANGED',					4),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_MOBILE',					3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_NAVAL',						5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_NAVAL_RECON',				5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_NAVAL_GROWTH',				6),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_NAVAL_TILE_IMPROVEMENT',	8),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_AIR',						5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_EXPANSION',					5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_GROWTH',					8),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_TILE_IMPROVEMENT',			3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_INFRASTRUCTURE',			7),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_PRODUCTION',				6),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_GOLD',						4),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_SCIENCE',					5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_CULTURE',					7),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_HAPPINESS',					8),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_GREAT_PEOPLE',				5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_WONDER',					3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_RELIGION',					9),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_DIPLOMACY',					11),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_SPACESHIP',					3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_WATER_CONNECTION',			7),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_NUKE',						4),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_USE_NUKE',					2),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_ESPIONAGE',					4),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_ANTIAIR',					5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_AIR_CARRIER',				5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_ARCHAEOLOGY',				8),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_I_LAND_TRADE_ROUTE',		3),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_I_SEA_TRADE_ROUTE',			7),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_I_TRADE_ORIGIN',			5),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_I_TRADE_DESTINATION',		7),
		('LEADER_JWW_XANANA_GUSMAO',	'FLAVOR_AIRLIFT',					5);

INSERT INTO Leader_Traits
		(LeaderType,					TraitType)
VALUES	('LEADER_JWW_XANANA_GUSMAO',	'TRAIT_JWW_BALIBOHONG_DELARATION');

-------------------------------------------
--Trait (Balibohong Declaration)
-------------------------------------------

INSERT INTO Traits
		(Type,								Description,								ShortDescription)
VALUES	('TRAIT_JWW_BALIBOHONG_DELARATION',	'TXT_KEY_TRAIT_JWW_BALIBOHONG_DELARATION',	'TXT_KEY_TRAIT_JWW_BALIBOHONG_DELARATION_SHORT');

INSERT INTO UnitPromotions
		(Type,						Description,					Help,								Sound,				CannotBeChosen,	DefenseMod,	PortraitIndex,	IconAtlas,			PediaType,		PediaEntry)
VALUES	('PROMOTION_JWW_TL_UA',		'TXT_KEY_PROMOTION_JWW_TL_UA',	'TXT_KEY_PROMOTION_JWW_TL_UA_HELP',	'AS2D_IF_LEVELUP',	1,				50,			59,				'ABILITY_ATLAS',	'PEDIA_SHARED',	'TXT_KEY_PROMOTION_JWW_TL_UA');

-------------------------------------------
--Diplomacy Responses
-------------------------------------------

INSERT INTO Diplomacy_Responses
		(LeaderType,					 ResponseType,									  Response,																	Bias)
VALUES	('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_ATTACKED_HOSTILE',                     'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_ATTACKED_GENERIC%',						500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_DEFEATED',                             'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_DEFEATED%',								500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_DOW_GENERIC',                          'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_DOW_GENERIC%',                          500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_EXPANSION_SERIOUS_WARNING',            'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_EXPANSION_SERIOUS_WARNING%',            500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_FIRST_GREETING',                       'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_FIRSTGREETING%',                        500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_GREETING_AT_WAR_HOSTILE',			  'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_GREETING_AT_WAR_HOSTILE%',              500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_GREETING_POLITE_HELLO',                'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_GREETING_POLITE_HELLO%',                500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_GREETING_NEUTRAL_HELLO',               'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_GREETING_NEUTRAL_HELLO%',               500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_GREETING_HOSTILE_HELLO',               'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_GREETING_HOSTILE_HELLO%',               500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',  'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',  500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_INFLUENTIAL_ON_AI',                    'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_INFLUENTIAL_ON_AI%',                    500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_INFLUENTIAL_ON_HUMAN',                 'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_INFLUENTIAL_ON_HUMAN%',					500),	
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_LETS_HEAR_IT',                         'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_LETS_HEAR_IT%',							500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_LUXURY_TRADE',                         'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_LUXURY_TRADE%',							500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_NO_PEACE',                             'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_NO_PEACE%',								500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_OPEN_BORDERS_EXCHANGE',                'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_OPEN_BORDERS_EXCHANGE%',				500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS',         'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_LOSEWAR%',                              500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_REPEAT_NO',                            'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_REPEAT_NO%',                            500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_RESPONSE_REQUEST',                     'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_RESPONSE_REQUEST%',						500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_RESPONSE_TO_BEING_DENOUNCED',		  'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_RESPONSE_TO_BEING_DENOUNCED%',          500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_TOO_SOON_NO_PEACE',                    'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_TOO_SOON_NO_PEACE_1%',                  500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_WINNER_PEACE_OFFER',                   'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_WINWAR%',                               500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_WORK_AGAINST_SOMEONE',                 'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_DENOUNCE%',								500),
		('LEADER_JWW_XANANA_GUSMAO',     'RESPONSE_WORK_WITH_US',                         'TXT_KEY_LEADER_JWW_XANANA_GUSMAO_DEC_FRIENDSHIP%',                       500);

-------------------------------------------
--Civilization (Timor-Leste)
-------------------------------------------

INSERT INTO Civilizations
		(Type,								Description,						Civilopedia,							CivilopediaTag,					Playable,	AIPlayable,	ShortDescription,							Adjective,									DefaultPlayerColor,				ArtDefineTag,						ArtStyleType,						ArtStyleSuffix,		ArtStylePrefix,		PortraitIndex,	IconAtlas,						AlphaIconAtlas,					MapImage,				DawnOfManQuote,								DawnOfManImage)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CIV_JWW_TIMOR-LESTE_DESC',	'TXT_KEY_CIV_JWW_TIMOR-LESTE_PEDIA',	'TXT_KEY_CIV5_JWW_TIMOR-LESTE',	1,			1,			'TXT_KEY_CIV_JWW_TIMOR-LESTE_SHORT_DESC',	'TXT_KEY_CIV_JWW_TIMOR-LESTE_ADJECTIVE',	'PLAYERCOLOR_JWW_TIMOR-LESTE',	'ART_DEF_CIVILIZATION_POLYNESIA',	'ART_DEF_CIVILIZATION_POLYNESIA',	'_ASIA',			'ASIAN',			1,				'JWW_TIMORLESTE_COLOR_ATLAS',	'JWW_TIMORLESTE_ALPHA_ATLAS',	'JWWTimorLesteMap.dds',	'TXT_KEY_CIV5_DAWN_JWW_TIMOR-LESTE_TEXT',	'GusmaoDOM.dds');

INSERT INTO Civilization_Leaders
		(CivilizationType,					LeaderheadType)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'LEADER_JWW_XANANA_GUSMAO');

INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType,					BuildingClassType,			BuildingType)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'BUILDINGCLASS_CONSTABLE',	'BUILDING_JWW_IGREJA_TIMORENSE');

INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType,					UnitClassType,		UnitType)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'UNITCLASS_MARINE',	'UNIT_JWW_FORCAS_DA_FALINTIL');

INSERT INTO Civilization_FreeBuildingClasses
		(CivilizationType,					BuildingClassType)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs
		(CivilizationType,					TechType)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'TECH_AGRICULTURE');

INSERT INTO Civilization_FreeUnits
		(CivilizationType,					UnitClassType,			UnitAIType,			Count)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'UNITCLASS_SETTLER',	'UNITAI_SETTLE',	1);

INSERT INTO Civilization_Religions
       (CivilizationType,				ReligionType)
VALUES ('CIVILIZATION_JWW_TIMOR-LESTE', 'RELIGION_CHRISTIANITY');

INSERT INTO Civilization_Start_Along_Ocean
		(CivilizationType,					StartAlongOcean)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	1);

INSERT INTO	Civilization_CityNames
		(CivilizationType,					CityName)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_0'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_1'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_2'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_3'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_4'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_5'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_6'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_7'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_8'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_9'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_10'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_11'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_12'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_13'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_14'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_15'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_16'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_17'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_18'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_19'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_20'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_21'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_22'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_23'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_24'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_25'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_26'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_27'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_28'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_29'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_30'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_31'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_32'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_33'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_34'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_35'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_36'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_37'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_38'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_39'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_40'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_41'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_42'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_43'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_44'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_45'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_46'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_47'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_48'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_49'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_50'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_51'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_52'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_53'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_54'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_55'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_56'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_57'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_58'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_59'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_60'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_61'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_62'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_63'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_64'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_65'),
		('CIVILIZATION_JWW_TIMOR-LESTE',	'TXT_KEY_CITY_NAME_JWW_TIMOR-LESTE_66');
				
INSERT INTO Civilization_SpyNames
		(CivilizationType,						SpyName)
VALUES	('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_0'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_1'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_2'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_3'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_4'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_5'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_6'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_7'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_8'),
		('CIVILIZATION_JWW_TIMOR-LESTE',		'TXT_KEY_SPY_NAME_JWW_TIMOR-LESTE_9');

--================================================================
--================================================================