-- Insert SQL Rules Here 
--==========================================================================================================================
-- Diplomacy_Responses
--==========================================================================================================================
INSERT INTO Diplomacy_Responses
(LeaderType,               ResponseType,                                         Response,                                                   Bias)
VALUES   
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_MINOR_CIV_COMPETITION',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_MINOR_CIV_COMPETITION%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_FIRST_GREETING',                            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_FIRSTGREETING%',                        2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DEFEATED',                                  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DEFEATED%',                          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_REPEAT_TOO_MUCH',                  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_REPEAT_TOO_MUCH%',                      2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_REPEAT_TRADE_TOO_MUCH',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_REPEAT_TRADE_TOO_MUCH%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_REPEAT',                   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_REPEAT_TOO_MUCH%',                      2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_HELLO',                    'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HELLO%',               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_POLITE_HELLO',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_POLITE_HELLO%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_AT_WAR%',           2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HUMAN_AT_WAR',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HUMAN_AT_WAR%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',       'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_AGGRESSIVE_MILITARY',              'TXT_KEY_LEADER_SPLATDAY_WILLIAM_AGGRESSIVE_MILITARY_WARNING%',             2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING',   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%',    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING',           'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_AGGRESSIVE_PLOT_BUYING%',         2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION',     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%',      2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_AGGRESSIVE_EXPANSION',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_AGGRESSIVE_EXPANSION%',           2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY',         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_FRIENDLY_STRONG_MILITARY%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY',          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_FRIENDLY_STRONG_ECONOMY%',        2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES',         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_FEW_CITIES%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY',         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_SMALL_ARMY%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER',       'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_IS_WARMONGER%',     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_TOO_SOON_FOR_DOF',                          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_TOO_SOON_FOR_DOF%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED',               'TXT_KEY_LEADER_SPLATDAY_WILLIAM_RESPONSE_TO_BEING_DENOUNCED%',             2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_WORK_AGAINST_SOMEONE',                      'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DENOUNCE%',                          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_AI_DOF_BACKSTAB',                           'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DENOUNCE%',                          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED',               'TXT_KEY_LEADER_SPLATDAY_WILLIAM_RESPONSE_TO_BEING_DENOUNCED%',             2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DOFED_FRIEND',                        'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOFED_FRIEND%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DOFED_ENEMY',                         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOFED_ENEMY%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DENOUNCED_ENEMY',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCED_ENEMY%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DENOUNCED_FRIEND',                    'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCED_FRIEND%',               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DOF_SO_AI_DOF',                       'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOF_SO_AI_DOF%',                  2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCE_SO_AI_DENOUNCE%',           2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE',                  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOF_SO_AI_DENOUNCE%',                2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_COOP_WAR_REQUEST',                          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_COOP_WAR_REQUEST%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_COOP_WAR_TIME',                             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_COOP_WAR_TIME%',                        2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_WORK_WITH_US',                              'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DEC_FRIENDSHIP%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_PLOT_BUYING_WARNING',                       'TXT_KEY_LEADER_SPLATDAY_WILLIAM_PLOT_BUYING_WARNING%',                  2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_PLOT_BUYING_SERIOUS_WARNING',               'TXT_KEY_LEADER_SPLATDAY_WILLIAM_PLOT_BUYING_SERIOUS_WARNING%',             2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_EXPANSION_SERIOUS_WARNING',                 'TXT_KEY_LEADER_SPLATDAY_WILLIAM_EXPANSION_SERIOUS_WARNING%',               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_EXPANSION_WARNING',                         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_EXPANSION_WARNING%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING',               'TXT_KEY_LEADER_SPLATDAY_WILLIAM_AGGRESSIVE_MILITARY_WARNING%',             2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_RETURNED_CIVILIAN',                         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_RETURNED_CIVILIAN%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DECLARATION_PROTECT_CITY_STATE',            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DECLARATION_PROTECT_CITY_STATE%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_BULLIED_PROTECTED_CITY_STATE',              'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BULLIED_PROTECTED_CITY_STATE%',            2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_PROTECTED_CITY_STATE',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_PROTECTED_CITY_STATEE%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DECLARATION_ABANDON_CITY_STATE',            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DECLARATION_ABANDON_CITY_STATE%',          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DONT_SETTLE_YES',                           'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DONT_SETTLE_YES%',                      2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DONT_SETTLE_NO',                            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DONT_SETTLE_NO%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_LUXURY_TRADE',                              'TXT_KEY_LEADER_SPLATDAY_WILLIAM_LUXURY_TRADE%',                         2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_OPEN_BORDERS_EXCHANGE',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_OPEN_BORDERS_EXCHANGE%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_REQUEST',                                   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_RESPONSE_REQUEST%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_HOSTILE',                          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_HOSTILE%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_WEAK_HOSTILE',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_HOSTILE%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_STRONG_HOSTILE',                   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_HOSTILE%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_EXCITED',                          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_EXCITED%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_WEAK_EXCITED',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_EXCITED%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_STRONG_EXCITED',                   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_EXCITED%',                     2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_SAD',                              'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_SAD%',                         2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_ATTACKED_BETRAYED',                         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_BETRAYED%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_GENERIC',                               'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_GENERIC%',                       2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_LAND',                                  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_LAND%',                          2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_WORLD_CONQUEST',                        'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_WORLD_CONQUEST%',                   2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_OPPORTUNITY',                           'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_OPPORTUNITY%',                      2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_DESPERATE',                             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_DESPERATE%',                        2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_DOW_REGRET',                                'TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_REGRET%',                        2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_TOO_SOON_NO_PEACE',                         'TXT_KEY_LEADER_SPLATDAY_WILLIAM_TOO_SOON_NO_PEACE%',                    2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                              2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',           'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                              2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                              2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_WE_ATTACKED_MINOR_BAD',                     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                              2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD',   'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_ATTACKED_MINOR_BAD',                  'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD',       'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD',     'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD',             'TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD',          'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD',            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_WE_ATTACKED_MINOR_GOOD',                    'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD',                 'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD',      'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD',    'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2),
('LEADER_SPLATDAY_WILLIAM', 'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD',            'TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD%',                               2);
--==========================================================================================================================
--==========================================================================================================================
INSERT INTO Language_en_US
(Tag,                                                 Text)
VALUES
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_FIRSTGREETING_1',                               'Greetings. I am William, born Stadtholder of Holland; now King by the will of my people. Can you say the same?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_FIRSTGREETING_2',                               'Greetings! I am William, rightful ruler of Holland and, dare I say, the herald of a unified Protestant Kingdom under Almighty God.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DEFEATED_1',                                    'I pray that you kill me now, so I will not see the fall of Holland.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_REPEAT_TOO_MUCH_1',                             'I admire your perseverence, but it amounts to nothing.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_REPEAT_TRADE_TOO_MUCH_1',                       'Do not use vain repetitions as the heathen do. Do you think you will be heard for your many words?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HELLO_1',                      'Ahh, a sinful nation. A people laden with iniquity. They have forsaken the Lord, and provoked to anger the Holy One. Why are you here?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_POLITE_HELLO_1',                       'It is not of little satisfaction to me that we are meeting today.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_AT_WAR_1',               'What are you doing here? You remind me of Satan, who stood before the Lord in the morning wanting to do nothing but torture the servant of the Lord.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HUMAN_AT_WAR_1',                       'How goes your war? Are you prepared to fight to the end?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_AGGRESSIVE_MILITARY_WARNING_1',                 'If you think to occupy the land of the Dutch, beware. You may find yourself overcome by the will of the people.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HOSTILE_AGGRESSIVE_MILITARY_WARNING_1',         'Your forces tremple on the truth and try to trample the will of my people. I will defend them until the last ditch.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_PLOT_BUYING_WARNING_1',                         'You seek to divide all land between you and your so-called allies like a cheap cloak. Do not think I do not realize.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_PLOT_BUYING_SERIOUS_WARNING_1',                 'The soldiers of Holland and the Protestant Kingdoms stand ready, to prevent you from grasping for our lands.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_AGGRESSIVE_PLOT_BUYING_1',             'Better is the sight of the eyes than the wandering of desire. You would be wise to take these words to heart.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING_1',     'You are a thief who does not come except to steal, and to kill, and to destroy. Get away from me.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_EXPANSION_WARNING_1',                           'You seem to believe that all people should be in your kingdom. But there will be a Kingdom of purity, upheld by God, which will not fail to stand.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_EXPANSION_SERIOUS_WARNING_1',                   'You want to conquer the lands to make a kingdom of darknees. But know this, we will stand against you.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_AGGRESSIVE_EXPANSION_1',               'Welcome, little conqueror. God demands an accounting from you, as you challenge him alone for Lordship of the earth.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_AGGRESSIVE_EXPANSION_1',       'Welcome, servant of the Devil. God has raised me up to oppose you, and by his grace I will overcome you.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_FRIENDLY_STRONG_MILITARY_1',           'It is excellent to see how many troops you have. Perhaps you could lend me some to help establish the throne?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_FRIENDLY_STRONG_ECONOMY_1',            'God has blessed you with many riches. Maybe you would support me in establishing the kingship?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_FEW_CITIES_1',           'Has the Lord struck you with consumption, or fever, with the sword or the scorching? There must be sin in your tents, because there are so few of them.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_SMALL_ARMY_1',           'The Judge, Gideon, went to war with more men than you do, and he was lead by the Angel of the Lord. You are led by yourself. You are just a fool.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GREETING_HOSTILE_HUMAN_IS_WARMONGER_1',         'Your trouble shall return upon your own head. Your violent dealing shall come down on your own crown.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_TOO_SOON_FOR_DOF_1',                            'You are too ambitious. I do not trust that you want unity over subtle conquest.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DENOUNCE_1',                                    'You are a tyrant, who thinks nothing of nation interest and occupy yourself only with your own animosities. The people will know of this.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DENOUNCE_2',                                    'You have played your hand too soon, devil.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_RESPONSE_TO_BEING_DENOUNCED_1',                 'Why are you persecuting me? Before God I am innocent.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOFED_FRIEND_1',                          'How beautiful upon the mountains are the feet of the ones who bring good news of peace between peaceful nations.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOFED_ENEMY_1',                           'The enemies of freedom, the enemies of God, they rally together and gnash their teeth.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCED_FRIEND_1',                      '{1_CivName} is innocent. Your lies will fall off them of and leave not a stain.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCED_ENEMY_1',                       'It is wisdom to call a dog a dog. Your wisdom is revealed in your treatment of {1_CivName}.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOF_SO_AI_DOF_1',                         'It is will distinct satisfaction that I accept {1_CivName} as an ally of the united kingdom.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DOF_SO_AI_DENOUNCE_1',                    '{1_CivName} is your ally? I have lost all respect for the tyrant who oppresses {1_CivName}.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_HUMAN_DENOUNCE_SO_AI_DENOUNCE_1',               'To keep the unity of the Kingdom, I have also written a declaration against {1_CivName}.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_COOP_WAR_REQUEST_1',                            'We are beset on all sides, but like the prophet Elijah, we pray for an army to arrive to destroy the wicked.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_COOP_WAR_TIME_1',                               'It is time for your yes to be proven as a yes.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DEC_FRIENDSHIP_1',                              'I am satisfied with your friendship and wish it to be made known that you are an ally of the people of Holland.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_RETURNED_CIVILIAN_1',                           'Your actions speak loauder than words, my friend.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_MINOR_CIV_COMPETITION_1',                       '{1_MinorCivName:textkey} is under the protection of the unified kingdom and, dare I say, the grace of the Almighty. Leave them alone.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_MINOR_CIV_COMPETITION_2',                       'The Lord God has given {1_MinorCivName:textkey} over to me. Do not interfere.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DECLARATION_PROTECT_CITY_STATE_1',              '{2_MajorCivName:textkey} announces to the world that it is now protecting {1_MinorCivName:textkey}. Attacking the City-State will greatly damage relations and may lead to war.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DECLARATION_ABANDON_CITY_STATE_1',              '{2_MajorCivName:textkey} has taken back its guarantee of protecting {1_MinorCivName:textkey}.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_PROTECTED_CITY_STATE_1',               'You have attacked {@1_MinorCivName}, and she calls out to us for protection.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_BULLIED_PROTECTED_CITY_STATE_1',                'You have attacked {@1_MinorCivName}, and she calls out to us for protection.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DONT_SETTLE_NO_1',                              'The ships of Holland must find ports to moor at in this time.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DONT_SETTLE_YES_1',                             'Forgive me for not considering the needs of those outside of my own country.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_LUXURY_TRADE_1',                                'This is an excellent offer. Thank you.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_OPEN_BORDERS_EXCHANGE_1',                       'There will be no way for us to defend our people if we do not work together.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_RESPONSE_REQUEST_1',                            'Consider this, I believe you will find it valuable.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_HOSTILE_1',                            'I will never see my country''s ruin. Even if I must die in the last ditch.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_EXCITED_1',                            'I see that you want to test the might of my soldiers, my navy, the will of the Dutch, and the hand of the Almighty!'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_SAD_1',                                'Another senseless, petty quarrel, that will be felt first and foremost by the people in our nations.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_ATTACKED_BETRAYED_1',                           'What is this? I wrote to you for aid!'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_GENERIC_1',                                 'Well, tyrant. Now is the time to draw arms and show your mettle.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_GENERIC_2',                                 'Every bullet has its billet. Where shall I billet the rounds in my chamber?'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_LAND_1',                                    'Your troops occupy much of the land that is rightfully part of the Kingdom of God.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_WORLD_CONQUEST_1',                          'All men, and all lands, will be unified as part of the Kingdom of God. Then the end will come.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_OPPORTUNITY_1',                             'I have received a letter from your own people, telling me that it is their will that I, and not you, am named sovereign King of their lands. Now, please: step aside so that there will not be bloodshed.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_DESPERATE_1',                               'There is but one certain means by which I can be sure never to see my country''s ruin: One of us has to die!'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_DOW_BETRAYAL_1',                                'I have received a letter from your own people, telling me that it is their will that I, and not you, am named sovereign King of their lands. Now, please: step aside so that there will not be bloodshed.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_TOO_SOON_NO_PEACE_1',                           'This war will not end until the people are liberated from your tyrrany.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_BAD_1',                                         'Ha! You think me foolish.'),
('TXT_KEY_LEADER_SPLATDAY_WILLIAM_GOOD_1',                                        'Yes. This is good for Holland -- and dare I say, Zealand as well!');