INSERT INTO Diplomacy_Responses
		(LeaderType,					ResponseType,									Response,																	Bias)
VALUES	('LEADER_PB_MORI_MOTONARI',	'RESPONSE_DEFEATED',							'TXT_KEY_LEADER_PB_MORI_MOTONARI_DEFEATED%',								1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_EXPANSION_SERIOUS_WARNING',			'TXT_KEY_LEADER_PB_MORI_MOTONARI_EXPANSION_SERIOUS_WARNING%',			1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_FIRST_GREETING',						'TXT_KEY_LEADER_PB_MORI_MOTONARI_FIRSTGREETING%',						1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_GREETING_HOSTILE_HELLO',				'TXT_KEY_LEADER_PB_MORI_MOTONARI_GREETING_HOSTILE_HELLO%',				1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_GREETING_NEUTRAL_HELLO',				'TXT_KEY_LEADER_PB_MORI_MOTONARI_GREETING_NEUTRAL_HELLO%',				1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_GREETING_POLITE_HELLO',				'TXT_KEY_LEADER_PB_MORI_MOTONARI_GREETING_POLITE_HELLO%',				1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',	'TXT_KEY_LEADER_PB_MORI_MOTONARI_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',	1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_REQUEST',								'TXT_KEY_LEADER_PB_MORI_MOTONARI_REQUEST%',								1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_DECLAREWAR',							'TXT_KEY_LEADER_PB_MORI_MOTONARI_DECLAREWAR%',							1),
		('LEADER_PB_MORI_MOTONARI', 'RESPONSE_HUMAN_DOFED_FRIEND',					'TXT_KEY_LEADER_PB_MORI_MOTONARI_HUMAN_DOFED_FRIEND%',					1),
		('LEADER_PB_MORI_MOTONARI',	'RESPONSE_HUMAN_DOF_SO_AI_DOF',					'TXT_KEY_LEADER_PB_MORI_MOTONARI_HUMAN_DOF_SO_AI_DOF%',					1);
-- ============================================================================
-- Cultural Influence
-- ============================================================================
-- Player is influential on the AI (Our people are wearing your blue jeans...)
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_PB_MORI_MOTONARI', 'RESPONSE_INFLUENTIAL_ON_AI', 'TXT_KEY_LEADER_PB_MORI_MOTONARI_INFLUENTIAL_ON_AI%', 500);
-- AI is influential on the player
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_PB_MORI_MOTONARI', 'RESPONSE_INFLUENTIAL_ON_HUMAN', 'TXT_KEY_LEADER_PB_MORI_MOTONARI_INFLUENTIAL_ON_HUMAN%', 500);